name: CI
on:
  pull_request:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Install QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/smartmatrixserver:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
