name: Publish Docker image
on:
  push:
    branches: [main]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Install QEMU
        uses: docker/setup-qemu-action@v2
      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/smartmatrixserver:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
